
const ActionTypes = {
  STORE_LOAD: 'STORE_LOAD',
  STORE_SETUP_DONE: 'STORE_SETUP_DONE',
  STORE_VIEW_LOAD: 'STORE_VIEW_LOAD',
  ATOM_INPUT: 'ATOM_INPUT',
  ATOM_CHANGE: 'ATOM_CHANGE',

  GRAPH_VIEW_DOUBLE_CLICK: 'SELECT',
  GRAPH_VIEW_SELECT_NODE: 'SELECT_NODE',
  GRAPH_VIEW_SELECT_EDGE: 'SELECT_EDGE',
  GRAPH_VIEW_DESELECT_NODE: 'DESELECT_NODE',
  GRAPH_VIEW_DESELECT_EDGE: 'DESELECT_EDGE',
  GRAPH_VIEW_HOVER_NODE: 'HOVER_NODE',
  GRAPH_VIEW_HOVER_EDGE: 'HOVER_EDGE',
  GRAPH_VIEW_BLUR_NODE: 'BLUR_NODE',
  GRAPH_VIEW_BLUR_EDGE: 'BLUR_EDGE',
  GRAPH_VIEW_CLICK: 'CLICK',
  GRAPH_VIEW_DOUBLE_CLICK: 'DOUBLE_CLICK'
};

export default ActionTypes;
